<?php
/*
* Config file with each demo data
*/

return array(
	'multi-purpose'		=>	array(
		'demoName'				=>	'Multi Purpose',
		'liveURL'				=>	'http://highgradelab.com/stash/multi-purpose/',
		'demoImg'				=>	'multi-purpose.jpg',
		'xmlContentFile'			=>	'multi-purpose.xml',
		'themeOptionsFile'			=>	'multi-purpose.json',
		'essentialGridFile'			=>	'multi-purpose.json',
		'revSliderZipFiles'			=>	'false',
		'homepage'				=>	'multi-purpose-homepage',
	),
	'business'		=>	array(
		'demoName'				=>	'Business',
		'liveURL'				=>	'http://highgradelab.com/stash/business/',
		'demoImg'				=>	'business.jpg',
		'xmlContentFile'			=>	'business.xml',
		'themeOptionsFile'			=>	'business.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	array('business-slider.zip'),
		'homepage'				=>	'business-homepage',
	),
	'corporate'		=>	array(
		'demoName'				=>	'Corporate',
		'liveURL'				=>	'http://highgradelab.com/stash/corporate/',
		'demoImg'				=>	'corporate.jpg',
		'xmlContentFile'			=>	'corporate.xml',
		'themeOptionsFile'			=>	'corporate.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	array('creative-frontpage.zip'),
		'homepage'				=>	'corporate-homepage',
	),
	'creative-agency'	=>	array(
		'demoName'				=>	'Creative Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/creative-agency/',
		'demoImg'				=>	'creative-agency.jpg',
		'xmlContentFile'			=>	'creative-agency.xml',
		'themeOptionsFile'			=>	'creative-agency.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'creative-agency-homepage',
	),
	'classic-business'	=>	array(
		'demoName'				=>	'Classic Business',
		'liveURL'				=>	'http://highgradelab.com/stash/classic-business/',
		'demoImg'				=>	'classic-business.jpg',
		'xmlContentFile'			=>	'classic-business.xml',
		'themeOptionsFile'			=>	'classic-business.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'classic-bussines-homepage',
	),
	'classic-agency'	=>	array(
		'demoName'				=>	'Classic Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/classic-agency/',
		'demoImg'				=>	'classic-agency.jpg',
		'xmlContentFile'			=>	'classic-agency.xml',
		'themeOptionsFile'			=>	'classic-agency.json',
		'essentialGridFile'			=>	'classic-agency.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'classicagency-homepage',
	),
	'branding-agency'	=>	array(
		'demoName'				=>	'Branding Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/branding-agency/',
		'demoImg'				=>	'branding-agency.jpg',
		'xmlContentFile'			=>	'branding-agency.xml',
		'themeOptionsFile'			=>	'branding-agency.json',
		'essentialGridFile'			=>	'branding-agency.json',
		'revSliderZipFiles'			=>	array('BrandingAgency.zip'),
		'homepage'				=>	'brandingagency-homepage',
	),
	'digital-business'	=>	array(
		'demoName'				=>	'Digital Business',
		'liveURL'				=>	'http://highgradelab.com/stash/digital-business/',
		'demoImg'				=>	'digital-business.jpg',
		'xmlContentFile'			=>	'digital-business.xml',
		'themeOptionsFile'			=>	'digital-business.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'digital-business-homepage',
	),
	'personal-page'		=>	array(
		'demoName'				=>	'Personal Page',
		'liveURL'				=>	'http://highgradelab.com/stash/personal-page/',
		'demoImg'				=>	'personal-page.jpg',
		'xmlContentFile'			=>	'personal-page.xml',
		'themeOptionsFile'			=>	'personal-page.json',
		'essentialGridFile'			=>	array('personal-page.json'),
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'personal-page-homepage',
	),
	'personal-creative'	=>	array(
		'demoName'				=>	'Personal Creative',
		'liveURL'				=>	'http://highgradelab.com/stash/personal-creative/',
		'demoImg'				=>	'personal-creative.jpg',
		'xmlContentFile'			=>	'personal-creative.xml',
		'themeOptionsFile'			=>	'personal-creative.json',
		'essentialGridFile'			=>	'personal-creative.json',
		'revSliderZipFiles'			=>	array('personal-creative.zip'),
		'homepage'				=>	'personal-creative-homepage',
	),
	'classic-studio'	=>	array(
		'demoName'				=>	'Classic Studio',
		'liveURL'				=>	'http://highgradelab.com/stash/classic-studio/',
		'demoImg'				=>	'classic-studio.jpg',
		'xmlContentFile'			=>	'classic-studio.xml',
		'themeOptionsFile'			=>	'classic-studio.json',
		'essentialGridFile'			=>	array('classic-studio.json'),
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'classic-studio-homepage',
	),
	'agency'		=>	array(
		'demoName'				=>	'Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/agency/',
		'demoImg'				=>	'agency.jpg',
		'xmlContentFile'			=>	'agency.xml',
		'themeOptionsFile'			=>	'agency.json',
		'essentialGridFile'			=>	'agency.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'agency-homepage',
	),
	'modern-business'	=>	array(
		'demoName'				=>	'Modern Business',
		'liveURL'				=>	'http://highgradelab.com/stash/modern-business/',
		'demoImg'				=>	'modern-business.jpg',
		'xmlContentFile'			=>	'modern-business.xml',
		'themeOptionsFile'			=>	'modern-business.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'modern-business-homepage',
	),
	'digital-agency'	=>	array(
		'demoName'				=>	'Digital Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/digital-agency/',
		'demoImg'				=>	'digital-agency.jpg',
		'xmlContentFile'			=>	'digital-agency.xml',
		'themeOptionsFile'			=>	'digital-agency.json',
		'essentialGridFile'			=>	'digital-agency.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'digital-agency-homepage',
	),
	'creative-studio'	=>	array(
		'demoName'				=>	'Creative Studio',
		'liveURL'				=>	'http://highgradelab.com/stash/creative-studio/',
		'demoImg'				=>	'creative-studio.jpg',
		'xmlContentFile'			=>	'creative-studio.xml',
		'themeOptionsFile'			=>	'creative-studio.json',
		'essentialGridFile'			=>	'creative-studio.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'creative-studio-homepage',
	),
	'consulting'		=>	array(
		'demoName'				=>	'Consulting',
		'liveURL'				=>	'http://highgradelab.com/stash/consulting/',
		'demoImg'				=>	'consulting.jpg',
		'xmlContentFile'			=>	'consulting.xml',
		'themeOptionsFile'			=>	'consulting.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'consulting-homepage',
	),
	'conference'		=>	array(
		'demoName'				=>	'Conference',
		'liveURL'				=>	'http://highgradelab.com/stash/conference/',
		'demoImg'				=>	'conference.jpg',
		'xmlContentFile'			=>	'conference.xml',
		'themeOptionsFile'			=>	'conference.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	array('conference-carousel.zip'),
		'homepage'				=>	'conference-homepage',
	),
	'marketing-agency'	=>	array(
		'demoName'				=>	'Marketing Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/marketing-agency/',
		'demoImg'				=>	'marketing-agency.jpg',
		'xmlContentFile'			=>	'marketing-agency.xml',
		'themeOptionsFile'			=>	'marketing-agency.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'marketing-agency-homepage',
	),
	'personal-resume'	=>	array(
		'demoName'				=>	'Personal Resume',
		'liveURL'				=>	'http://highgradelab.com/stash/personal-resume/',
		'demoImg'				=>	'personal-resume.jpg',
		'xmlContentFile'			=>	'personal-resume.xml',
		'themeOptionsFile'			=>	'personal-resume.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'personal-resume-homepage',
	),
	'product-showcase'	=>	array(
		'demoName'				=>	'Product Showcase',
		'liveURL'				=>	'http://highgradelab.com/stash/product-showcase/',
		'demoImg'				=>	'product-showcase.jpg',
		'xmlContentFile'			=>	'product-showcase.xml',
		'themeOptionsFile'			=>	'product-showcase.json',
		'essentialGridFile'			=>	'product-showcase.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'product-showcase-homepage',
	),
	'classic-shop'		=>	array(
		'demoName'				=>	'Classic Shop',
		'liveURL'				=>	'http://highgradelab.com/stash/classic-shop/',
		'demoImg'				=>	'classic-shop.jpg',
		'xmlContentFile'			=>	'classic-shop.xml',
		'themeOptionsFile'			=>	'classic-shop.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'classic-shop-homepage',
	),
	'freelancer'		=>	array(
		'demoName'				=>	'Freelancer',
		'liveURL'				=>	'http://highgradelab.com/stash/freelancer/',
		'demoImg'				=>	'freelancer.jpg',
		'xmlContentFile'			=>	'freelancer.xml',
		'themeOptionsFile'			=>	'freelancer.json',
		'essentialGridFile'			=>	'freelancer.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'freelancer-homepage',
	),
	'landing-page'		=>	array(
		'demoName'				=>	'Landing Page',
		'liveURL'				=>	'http://highgradelab.com/stash/landing-page/',
		'demoImg'				=>	'landing-page.jpg',
		'xmlContentFile'			=>	'landing-page.xml',
		'themeOptionsFile'			=>	'landing-page.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'landing-page-home',
	),
	'app-showcase'		=>	array(
		'demoName'				=>	'App Showcase',
		'liveURL'				=>	'http://highgradelab.com/stash/app-showcase/',
		'demoImg'				=>	'app-showcase.jpg',
		'xmlContentFile'			=>	'app-showcase.xml',
		'themeOptionsFile'			=>	'app-showcase.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'app-showcase-homepage',
	),
	'startup'		=>	array(
		'demoName'				=>	'Startup',
		'liveURL'				=>	'http://highgradelab.com/stash/startup/',
		'demoImg'				=>	'startup.jpg',
		'xmlContentFile'			=>	'startup.xml',
		'themeOptionsFile'			=>	'startup.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'statup-homepage',
	),
	'product-promo'		=>	array(
		'demoName'				=>	'Product Promo',
		'liveURL'				=>	'http://highgradelab.com/stash/product-promo/',
		'demoImg'				=>	'product-promo.jpg',
		'xmlContentFile'			=>	'product-promo.xml',
		'themeOptionsFile'			=>	'product-promo.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'product-promo-homepage',
	),
	'tech-company'		=>	array(
		'demoName'				=>	'Tech Company',
		'liveURL'				=>	'http://highgradelab.com/stash/tech-company/',
		'demoImg'				=>	'tech-company.jpg',
		'xmlContentFile'			=>	'tech-company.xml',
		'themeOptionsFile'			=>	'tech-company.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'tech-company-homepage',
	),
	'parallax'		=>	array(
		'demoName'				=>	'Parallax',
		'liveURL'				=>	'http://highgradelab.com/stash/parallax/',
		'demoImg'				=>	'parallax.jpg',
		'xmlContentFile'			=>	'parallax.xml',
		'themeOptionsFile'			=>	'parallax.json',
		'essentialGridFile'			=>	'parallax.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'parallax-homepage',
	),
	'minimal-shop'		=>	array(
		'demoName'				=>	'Minimal Shop',
		'liveURL'				=>	'http://highgradelab.com/stash/minimal-shop/',
		'demoImg'				=>	'minimal-shop.jpg',
		'xmlContentFile'			=>	'minimal-shop.xml',
		'themeOptionsFile'			=>	'minimal-shop.json',
		'essentialGridFile'			=>	array('minimal-shop.json'),
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'minimal-shop-homepage',
	),
	'saas'			=>	array(
		'demoName'				=>	'Saas',
		'liveURL'				=>	'http://highgradelab.com/stash/saas/',
		'demoImg'				=>	'saas.jpg',
		'xmlContentFile'			=>	'saas.xml',
		'themeOptionsFile'			=>	'saas.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'saas-homepage',
	),
	'simple-business'	=>	array(
		'demoName'				=>	'Simple Business',
		'liveURL'				=>	'http://highgradelab.com/stash/simple-business/',
		'demoImg'				=>	'simple-business.jpg',
		'xmlContentFile'			=>	'simple-business.xml',
		'themeOptionsFile'			=>	'simple-business.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'simple-bussines-homepage',
	),
	'minimal-portfolio'	=>	array(
		'demoName'				=>	'Minimal Portfolio',
		'liveURL'				=>	'http://highgradelab.com/stash/minimal-portfolio/',
		'demoImg'				=>	'minimal-portfolio.jpg',
		'xmlContentFile'			=>	'minimal-portfolio.xml',
		'themeOptionsFile'			=>	'minimal-portfolio.json',
		'essentialGridFile'			=>	'minimal-portfolio.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'minimal-portfolio-homepage',
	),
	'company-presentation'	=>	array(
		'demoName'				=>	'Company Presentation',
		'liveURL'				=>	'http://highgradelab.com/stash/company-presentation/',
		'demoImg'				=>	'company-presentation.jpg',
		'xmlContentFile'			=>	'company-presentation.xml',
		'themeOptionsFile'			=>	'company-presentation.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'company-presentation-homepage',
	),
	'vcard'			=>	array(
		'demoName'				=>	'Vcard',
		'liveURL'				=>	'http://highgradelab.com/stash/vcard/',
		'demoImg'				=>	'vcard.jpg',
		'xmlContentFile'			=>	'vcard.xml',
		'themeOptionsFile'			=>	'vcard.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	array('vCard.zip'),
		'homepage'				=>	'vcard-homepage',
	),
	'dark-landing-page'	=>	array(
		'demoName'				=>	'Dark Landing Page',
		'liveURL'				=>	'http://highgradelab.com/stash/dark-landing-page/',
		'demoImg'				=>	'dark-landing-page.jpg',
		'xmlContentFile'			=>	'dark-landing-page.xml',
		'themeOptionsFile'			=>	'dark-landing-page.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'dark-landing-page-home',
	),
	'dark-business'		=>	array(
		'demoName'				=>	'Dark Business',
		'liveURL'				=>	'http://highgradelab.com/stash/dark-business/',
		'demoImg'				=>	'dark-business.jpg',
		'xmlContentFile'			=>	'dark-business.xml',
		'themeOptionsFile'			=>	'dark-business.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	array('dark-business.zip'),
		'homepage'				=>	'dark-business-homepage',
	),
	'dark-agency'		=>	array(
		'demoName'				=>	'Dark Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/dark-agency/',
		'demoImg'				=>	'dark-agency.jpg',
		'xmlContentFile'			=>	'dark-agency.xml',
		'themeOptionsFile'			=>	'dark-agency.json',
		'essentialGridFile'			=>	'dark-agency.json',
		'revSliderZipFiles'			=>	array('dark-agency.zip'),
		'homepage'				=>	'dark-agency-homepage',
	),
	'design-studio'		=>	array(
		'demoName'				=>	'Design Studio',
		'liveURL'				=>	'http://highgradelab.com/stash/design-studio/',
		'demoImg'				=>	'design-studio.jpg',
		'xmlContentFile'			=>	'design-studio.xml',
		'themeOptionsFile'			=>	'design-studio.json',
		'essentialGridFile'			=>	array('design-studio.json'),
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'design-studio-homepage',
	),
	'digital-startup'	=>	array(
		'demoName'				=>	'Digital Startup',
		'liveURL'				=>	'http://highgradelab.com/stash/digital-startup/',
		'demoImg'				=>	'digital-startup.jpg',
		'xmlContentFile'			=>	'digital-startup.xml',
		'themeOptionsFile'			=>	'digital-startup.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'digital-startup-homepage',
	),
	'corporation'		=>	array(
		'demoName'				=>	'Corporation',
		'liveURL'				=>	'http://highgradelab.com/stash/corporation/',
		'demoImg'				=>	'corporation.jpg',
		'xmlContentFile'			=>	'corporation.xml',
		'themeOptionsFile'			=>	'corporation.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'corporation-homepage',
	),
	'online-agency'		=>	array(
		'demoName'				=>	'Online Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/online-agency/',
		'demoImg'				=>	'online-agency.jpg',
		'xmlContentFile'			=>	'online-agency.xml',
		'themeOptionsFile'			=>	'online-agency.json',
		'essentialGridFile'			=>	'online-agency.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'online-agency-homepage',
	),
	'single-product-showcase'	=>	array(
		'demoName'				=>	'Single Product Showcase',
		'liveURL'				=>	'http://highgradelab.com/stash/single-product-showcase/',
		'demoImg'				=>	'single-product-showcase.jpg',
		'xmlContentFile'			=>	'single-product-showcase.xml',
		'themeOptionsFile'			=>	'single-product-showcase.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'single-product-showcase-homepage',
	),
	'dark-freelancer'	=>	array(
		'demoName'				=>	'Dark Freelancer',
		'liveURL'				=>	'http://highgradelab.com/stash/dark-freelancer/',
		'demoImg'				=>	'dark-freelancer.jpg',
		'xmlContentFile'			=>	'dark-freelancer.xml',
		'themeOptionsFile'			=>	'dark-freelancer.json',
		'essentialGridFile'			=>	array('dark-freelancer.json'),
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'dark-freelancer-homepage',
	),
	'dark-online-agency'	=>	array(
		'demoName'				=>	'Dark Online Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/dark-online-agency/',
		'demoImg'				=>	'dark-online-agency.jpg',
		'xmlContentFile'			=>	'dark-online-agency.xml',
		'themeOptionsFile'			=>	'dark-online-agency.json',
		'essentialGridFile'			=>	'dark-online-agency.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'dark-online-agency-homepage',
	),
	'furniture-shop'	=>	array(
		'demoName'				=>	'Furniture Shop',
		'liveURL'				=>	'http://highgradelab.com/stash/furniture-shop/',
		'demoImg'				=>	'furniture-shop.jpg',
		'xmlContentFile'			=>	'furniture-shop.xml',
		'themeOptionsFile'			=>	'furniture-shop.json',
		'essentialGridFile'			=>	'furniture-shop.json',
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'furniture-shop-homepage',
	),
	'financial-services'	=>	array(
		'demoName'				=>	'Financial Services',
		'liveURL'				=>	'http://highgradelab.com/stash/financial-services/',
		'demoImg'				=>	'financial-services.jpg',
		'xmlContentFile'			=>	'financial-services.xml',
		'themeOptionsFile'			=>	'financial-services.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'financial-services-homepage',
	),
	'online-marketing-agency'	=>	array(
		'demoName'				=>	'Online Marketing Agency',
		'liveURL'				=>	'http://highgradelab.com/stash/online-marketing-agency/',
		'demoImg'				=>	'online-marketing-agency.jpg',
		'xmlContentFile'			=>	'online-marketing-agency.xml',
		'themeOptionsFile'			=>	'online-marketing-agency.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	'online-marketing-agency-homepage',
	),
	'video-landing-page'	=>	array(
		'demoName'				=>	'Video Landing Page',
		'liveURL'				=>	'http://highgradelab.com/stash/video-landing-page/',
		'demoImg'				=>	'video-landing-page.jpg',
		'xmlContentFile'			=>	'video-landing-page.xml',
		'themeOptionsFile'			=>	'video-landing-page.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	array('video-landing-page.zip'),
		'homepage'				=>	'video-landingpage-homepage',
	),
	'inner-pages'		=>	array(
		'demoName'				=>	'Inner Pages',
		'liveURL'				=>	'http://highgradelab.com/stash/inner-pages/',
		'demoImg'				=>	'inner-pages.jpg',
		'xmlContentFile'			=>	'inner-pages.xml',
		'themeOptionsFile'			=>	'inner-pages.json',
		'essentialGridFile'			=>	false,
		'revSliderZipFiles'			=>	false,
		'homepage'				=>	false,
	),
	
	
)
?>
